#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime
# environment changes to make the snap work here.  You may also insert
# security confinement/deprecation/obsoletion notice of the snap here.

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

export HOME="${SNAP_USER_COMMON}"

script_dir="$(
    dirname "$(
        realpath \
            --strip \
            "${BASH_SOURCE[0]}"
    )"
)"

declare -a java_args=()

jvm_heap_memory_max="$(snapctl get jvm.xmx)"

if test -n "${jvm_heap_memory_max}"; then
    java_args+=(-Xmx"${jvm_heap_memory_max}")
fi

# workaround bash <=4.2
set +o nounset

# Finally run the next part of the command chain
exec java "${java_args[@]}" -jar "${SNAP:-${script_dir}/..}"/sbt.jar "${@}"
