#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime
# environment changes to make the snap work here.  You may also insert
# security confinement/deprecation/obsoletion notice of the snap here.

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

#export IMPORTANT_ENVIRONMENT_VARIABLE=value

script_dir="$(
    dirname "$(
        realpath \
            --strip \
            "${BASH_SOURCE[0]}"
    )"
)"

declare -a java_args=()
declare -a app_args=()

until test "${#}" -eq 0; do
    case "${1}" in
        -Xmx*)
            java_args+=("${1}")
        ;;
        *)
            app_args+=("${1}")
        ;;
    esac
    shift 1
done

# Finally run the next part of the command chain
exec java "${java_args[@]}" -jar "${SNAP:-${script_dir}/..}"/sbt.jar "${app_args[@]}"
