%YAML 1.1
---
# Snapcraft Recipe for BFG Repo-Cleaner
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft format
#   https://docs.snapcraft.io/the-snapcraft-format/8337
# * Snap Documentation
#   https://docs.snapcraft.io
# * Topics under the doc category in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft
name: bfg
title: BFG Repo-Cleaner
summary: Removes large or troublesome blobs like git-filter-branch does, but faster
description: |
  The BFG is a simpler, faster alternative to [`git-filter-branch`][1] for cleansing bad data out of your Git repository history:

  * Removing **Crazy Big Files**
  * Removing **Passwords**, **Credentials** & other **Private data**

  The `git-filter-branch` command is enormously powerful and can do things that the BFG can't - but the BFG is _much_ better for the tasks above, because:

  * [Faster][2] : **10 - 720x** faster
  * [Simpler][3] : The BFG isn't particularily clever, but _is_ focused on making the above tasks easy
  * Beautiful : If you need to, you can use the beautiful Scala language to customise the BFG. Which has got to be better than Bash scripting at least some of the time.

  [1]: http://git-scm.com/docs/git-filter-branch
  [2]: https://rtyley.github.io/bfg-repo-cleaner/#speed
  [3]: https://rtyley.github.io/bfg-repo-cleaner/#examples

  **Snap-specific notes**

  You can adjust JVM memory allocation via adding the Java -Xmx arguments to the sbt command-line, example:

      sbt -Xmx2048m ...

  No other JVM parameters are supported as of now.

# The path of icon to represent the snap, relative to the source tree directory
# Only PNG or SVG image is supported, dimension must be greater than 256x256px
icon: snap/gui/bfg.png

# The license of this application, in SPDX format
# NOTE: Currently only supports SPDX 2.1 license expressions, as described in Appendix IV of
# https://spdx.org/spdx-specification-21-web-version
# Supported expressions:
# https://github.com/snapcore/snapd/blob/HEAD/spdx/licenses.go
license: GPL-3.0

# Version string just for humans, typically '1.2+git' or '1.3.2'
# The wrapping single quotes are often required to avoid the version string
# being accidentally interpreted as a YAML non-string(like '1', '1.2').
# http://yaml.org/type
# https://arp242.net/weblog/yaml_probably_not_so_great_after_all.html#surprising-behaviour
# NOTE: This key is mutual exclusive with the `adopt-info` key
#version: Derived from the part specified by the `adopt-info` property

# Extract metadata from the main snap part
# https://forum.snapcraft.io/t/extracting-information-from-sources-in-snapcraft-parts/4642
adopt-info: main

# Snapd feature set and version the snap requires in order to work
# https://forum.snapcraft.io/t/snapcraft-top-level-metadata/8334#heading--assumes
assumes:
- command-chain

# Base runtime
# The common runtime for the snap to run on, or `bare` for static linked applications
base: core20
# https://docs.snapcraft.io/snapcraft-top-level-metadata/8334#heading--base

# Security confinement
# Use `devmode` to getting started
# Flip to `strict` once you have the right plugs and slots,
# or `classic` once you determine that strict confinement is not currently possible
confinement: strict

# Snap Grade
# Use `devel` to getting started
# Flip to `stable` once you determine that the snap is matured, only `stable` grade
# snaps can be promoted to `candidate` and `stable` channels
grade: devel

# Run `snapcraft help sources` for supported keywords on pulling a part's source ingredients
# Run `snapcraft plugins` for supported build helper plugins
# Run `snapcraft help plugins` for supported keywords on building a part
# For `override-*` scriptlets used to modify behavior of certain part's lifecycle phase, check out:
# https://docs.snapcraft.io/scriptlets/4892
parts:
  # Files to patch the files in the snap
  # patching:
  #   source: snap/local/patching
  #   plugin: dump
  #   organize:
  #     '*': patching/
  #   prime:
  #   - -*

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
    - -bin/README.*

  # Programs to modify the behavior of each step of the snapcraft lifecycles
  # scriptlets:
  #   source: snap/local/scriptlets
  #   plugin: dump
  #   organize:
  #     '*': scriptlets/
  #   prime:
  #   - -*

  # Stage snap for fixing the glibc locales(and gnu gettext I18N support)
  # This part is only required for non GUI apps that don't uses the desktop-launch launchers
  #locales-launch:
    #plugin: nil
    #stage-snaps:
    #- locales-launch
    #stage-packages:
    # For localedef(1)
    #- libc-bin

    # For locale data used by localedef(1)
    #- locales

    # All pre-generated locale data
    # DISABLED: Lots of duplicate data will be included in snap when this is staged, unless the target machine has no resource to generate them in runtime otherwise not using it
    #
    #   Lack of compiled locales breaks gettext based localisation - snapcraft - snapcraft.io
    #   https://forum.snapcraft.io/t/lack-of-compiled-locales-breaks-gettext-based-localisation/3758
    #
    #- locales-all

  # Check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    plugin: nil
    build-packages:
    - git
    stage-snaps:
    - selective-checkout
    prime:
    - -*

  main:
    after:
    - selective-checkout

    build-packages:
      - openjdk-8-jdk-headless

    source: https://github.com/rtyley/bfg-repo-cleaner.git
    source-depth: 200
    override-pull: |
      set -o nounset

      snapcraftctl pull

      "${SNAPCRAFT_STAGE}"/scriptlets/selective-checkout \
        --stable-tag-pattern='^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'

    plugin: nil

    override-build: |
      echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
      apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 642AC823
      sudo apt-get update
      sudo apt-get install -y sbt
      sbt compile
      sbt bfg/assembly
      jarfile="$(
        find \
          bfg/target \
          -name '*.jar' \
          | head \
            --lines=1
      )"
      install \
        --mode=0644 \
        "${jarfile}" \
        "${SNAPCRAFT_PART_INSTALL}"/sbt.jar

    stage-packages:
      - openjdk-8-jre-headless

    prime:
      - -usr/share/X11
      - -etc/X11
      - -etc/fonts
    override-prime: |
      set -o nounset

      snapcraftctl prime

      ln \
        --symbolic \
        --force \
        ../usr/lib/jvm/java-8-openjdk-amd64/bin/java \
        bin/java

# Apps that are exposed by the snap package
# If the _app_name_ is identical with the _snap_name_ it can be directly run
# with `_snap_name_` or `snap run _snap_name_` commands, otherwise it can only be run
# via `_snap_name_._app_name_` or `snap run _snap_name_._app_name_`
apps:
  bfg:
    # The adapter to set up runtime environment at the launch of the snap
    # NOTE: The `command-chain` property is only supported by the `full` adapter
    adapter: full

    # An *relative path* to an executable file root from the `prime` directory to be executed, and its command-line arguments
    # NOTE: The right angle bracket at the beginning of the value of the `command` keyword starts a YAML folded style block scalar, refer the following spec document for more info: http://yaml.org/spec/1.2/spec.html#id2796251
    command: bin/bfg-launch

    # The commands that are run, in order, before running the one specified by the `command` key
    # command-chain:
    # - bin/launcher

    environment:
      # Hardcode locale available in snap runtime
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

# Refer the following documentation for asserting interface plugs and slots in a security confined snap:
# Interface management - doc - snapcraft.io
# https://docs.snapcraft.io/interface-management/6154
# Supported interfaces - doc - snapcraft.io
# https://docs.snapcraft.io/supported-interfaces/7744
# Non-A/C: Non-autoconnect interface
plugs:
  # Regular files access
  home:
  removable-media: # Non-A/C

  # Application-specific files access
  # The auto-connection requires store grant
  # https://forum.snapcraft.io/t/the-personal-files-interface/9357
  # https://forum.snapcraft.io/t/the-system-files-interface/9358
  config-git:
    interface: personal-files
    read:
    - $HOME/.gitconfig

#slots:
